# Generated by Django 5.2.12 on 2026-03-13 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeType',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CodeTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INTRO', 'Introduction'), ('DISCONT', 'Discontinuation'), ('PIPO', 'PIPO')], max_length=7)),
                ('code_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='events.codetype')),
            ],
        ),
        migrations.CreateModel(
            name='Discontinuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_code', models.BigIntegerField()),
                ('code_transition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discontinuation', to='events.codetransition')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('iso_country_code', models.CharField(max_length=2)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='codetransition',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='events.event'),
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_code', models.BigIntegerField()),
                ('code_transition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='introduction', to='events.codetransition')),
            ],
        ),
        migrations.CreateModel(
            name='Pipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_code', models.BigIntegerField()),
                ('po_code', models.BigIntegerField()),
                ('code_transition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipo', to='events.codetransition')),
            ],
            options={
                'verbose_name': 'PIPO',
                'verbose_name_plural': 'PIPOs',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['iso_country_code'], name='events_even_iso_cou_660d89_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='events_even_date_5e8e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='codetransition',
            index=models.Index(fields=['type'], name='events_code_type_baa04f_idx'),
        ),
    ]
