# Generated by Django 6.0.3 on 2026-03-15 15:34

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INTRO", "Introduction"),
                            ("DISCONT", "Discontinuation"),
                            ("chain", "chain"),
                        ],
                        max_length=7,
                    ),
                ),
                ("date", models.DateField()),
            ],
            options={
                "ordering": ["date", "pk"],
            },
        ),
        migrations.CreateModel(
            name="CodeType",
            fields=[
                ("id", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("families_dirty", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Chain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("introduction_code", models.BigIntegerField()),
                ("discontinuation_code", models.BigIntegerField()),
                (
                    "code_transition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain",
                        to="events.codetransition",
                    ),
                ),
            ],
            options={
                "verbose_name": "chain",
                "verbose_name_plural": "chains",
            },
        ),
        migrations.AddField(
            model_name="codetransition",
            name="code_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transitions",
                to="events.codetype",
            ),
        ),
        migrations.CreateModel(
            name="Discontinuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("discontinuation_code", models.BigIntegerField()),
                (
                    "code_transition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discontinuation",
                        to="events.codetransition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "iso_country_code",
                    models.ForeignKey(
                        db_column="iso_country_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="events.country",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="codetransition",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transitions",
                to="events.event",
            ),
        ),
        migrations.CreateModel(
            name="Introduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("introduction_code", models.BigIntegerField()),
                (
                    "code_transition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="introduction",
                        to="events.codetransition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodeState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("DISCONTINUED", "Discontinued")],
                        max_length=13,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(default=datetime.date(9999, 12, 31))),
                (
                    "code_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.codetype"
                    ),
                ),
                (
                    "iso_country_code",
                    models.ForeignKey(
                        db_column="iso_country_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.country",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["iso_country_code", "code_type", "code"],
                        name="events_code_iso_cou_2ac4a4_idx",
                    ),
                    models.Index(fields=["status"], name="events_code_status_d4b578_idx"),
                ],
                "unique_together": {("iso_country_code", "code_type", "code", "start_date")},
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["iso_country_code"], name="events_even_iso_cou_660d89_idx"),
        ),
        migrations.AddIndex(
            model_name="codetransition",
            index=models.Index(fields=["type"], name="events_code_type_baa04f_idx"),
        ),
        migrations.AddIndex(
            model_name="codetransition",
            index=models.Index(fields=["date"], name="events_code_date_454971_idx"),
        ),
    ]
