services:
  chains:
    image: durczokj/chains:latest
    container_name: chains
    ports:
      - "8081:8080"
    volumes:
      - db-data:/app/data
    environment:
      - DB_PATH=/app/data/db.sqlite3
      - SCRIPT_NAME=/chains
    restart: unless-stopped

volumes:
  db-data:
