# Generated by Django 5.2.12 on 2026-03-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('lifecycles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationlink',
            name='source_transition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_links', to='events.codetransition'),
        ),
    ]
