# Generated by Django 6.0.3 on 2026-03-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identifier", models.CharField(max_length=255, unique=True)),
                ("iso_country_code", models.CharField(db_index=True, max_length=2)),
                (
                    "code_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_families",
                        to="events.codetype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product families",
                "ordering": ["iso_country_code", "identifier"],
            },
        ),
        migrations.CreateModel(
            name="Generation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.BigIntegerField()),
                ("iso_country_code", models.CharField(db_index=True, max_length=2)),
                (
                    "discontinuation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discontinued_generations",
                        to="events.codetransition",
                    ),
                ),
                (
                    "introduction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="introduced_generations",
                        to="events.codetransition",
                    ),
                ),
                (
                    "product_family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generations",
                        to="families.productfamily",
                    ),
                ),
            ],
            options={
                "ordering": ["introduction__date"],
            },
        ),
        migrations.CreateModel(
            name="GenerationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="successor_links",
                        to="families.generation",
                    ),
                ),
                (
                    "source_transition",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_links",
                        to="events.codetransition",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predecessor_links",
                        to="families.generation",
                    ),
                ),
            ],
            options={
                "unique_together": {("predecessor", "successor")},
            },
        ),
    ]
