# Generated by Django 6.0.2 on 2026-03-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generation",
            name="code",
        ),
        migrations.RemoveField(
            model_name="generation",
            name="iso_country_code",
        ),
    ]
