# Generated by Django 6.0.2 on 2026-03-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("families", "0002_remove_generation_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfamily",
            name="iso_country_code",
            field=models.ForeignKey(
                db_column="iso_country_code",
                on_delete=django.db.models.deletion.CASCADE,
                to="events.country",
            ),
        ),
    ]
